import {
    Wallet, Briefcase, Building, TrendingUp, Gift, PlusCircle,
    MoreHorizontal, Home, Zap, Wifi, Shield, CreditCard,
    UtensilsCrossed, ShoppingCart, Car, Truck, ShoppingBag,
    Film, Plane, Repeat, Heart, Book, ArrowDownCircle,
    PiggyBank, Bike, ParkingCircle, ArrowUpCircle, RefreshCw,
    Smartphone, Coffee, PawPrint, Baby, Pill, Dumbbell,
    WashingMachine, Receipt, Coins, Umbrella, GraduationCap,
    Bus, Scissors, Gamepad2, Landmark, Music,
    Fuel, Wrench, Stethoscope, HeartPulse, Cake, Pizza, Salad,
    Beer, Wine, Cigarette, Palette, Camera, Tv, Headphones,
    Trophy, Bell, Phone, Mail, Users, User, MapPin, Globe,
    Anchor, Ship, Train, Hammer, ShoppingBasket, Store,
    Cat, Dog, Fish, Flower2, TreePine, Sun, Cloud, Star,
    Sparkles, Gem, Watch, Glasses, Shirt, Footprints,
    Banknote, HandCoins, Handshake, School, Church, Hospital,
    Syringe, Droplet, Flame, Battery, Router, Laptop, Monitor,
    Printer, Key, Lock, MapPinned, Backpack, Luggage, Ticket,
    type LucideProps
} from 'lucide-react'
import type { ElementType } from 'react'

export const ICON_MAP: Record<string, ElementType<LucideProps>> = {
    'wallet': Wallet,
    'briefcase': Briefcase,
    'building': Building,
    'trending-up': TrendingUp,
    'gift': Gift,
    'plus-circle': PlusCircle,
    'more-horizontal': MoreHorizontal,
    'home': Home,
    'zap': Zap,
    'wifi': Wifi,
    'shield': Shield,
    'credit-card': CreditCard,
    'utensils': UtensilsCrossed,
    'shopping-cart': ShoppingCart,
    'car': Car,
    'truck': Truck,
    'shopping-bag': ShoppingBag,
    'film': Film,
    'plane': Plane,
    'repeat': Repeat,
    'heart': Heart,
    'book': Book,
    'arrow-down-circle': ArrowDownCircle,
    'piggy-bank': PiggyBank,
    'bike': Bike,
    'parking-circle': ParkingCircle,
    'arrow-up-circle': ArrowUpCircle,
    'refresh-cw': RefreshCw,
    'smartphone': Smartphone,
    'coffee': Coffee,
    'paw-print': PawPrint,
    'baby': Baby,
    'pill': Pill,
    'dumbbell': Dumbbell,
    'washing-machine': WashingMachine,
    'receipt': Receipt,
    'coins': Coins,
    'umbrella': Umbrella,
    'graduation-cap': GraduationCap,
    'bus': Bus,
    'scissors': Scissors,
    'gamepad-2': Gamepad2,
    'landmark': Landmark,
    'music': Music,
    'fuel': Fuel,
    'wrench': Wrench,
    'stethoscope': Stethoscope,
    'heart-pulse': HeartPulse,
    'cake': Cake,
    'pizza': Pizza,
    'salad': Salad,
    'beer': Beer,
    'wine': Wine,
    'cigarette': Cigarette,
    'palette': Palette,
    'camera': Camera,
    'tv': Tv,
    'headphones': Headphones,
    'trophy': Trophy,
    'bell': Bell,
    'phone': Phone,
    'mail': Mail,
    'users': Users,
    'user': User,
    'map-pin': MapPin,
    'globe': Globe,
    'anchor': Anchor,
    'ship': Ship,
    'train': Train,
    'hammer': Hammer,
    'shopping-basket': ShoppingBasket,
    'store': Store,
    'cat': Cat,
    'dog': Dog,
    'fish': Fish,
    'flower': Flower2,
    'tree-pine': TreePine,
    'sun': Sun,
    'cloud': Cloud,
    'star': Star,
    'sparkles': Sparkles,
    'gem': Gem,
    'watch': Watch,
    'glasses': Glasses,
    'shirt': Shirt,
    'footprints': Footprints,
    'banknote': Banknote,
    'hand-coins': HandCoins,
    'handshake': Handshake,
    'school': School,
    'church': Church,
    'hospital': Hospital,
    'syringe': Syringe,
    'droplet': Droplet,
    'flame': Flame,
    'battery': Battery,
    'router': Router,
    'laptop': Laptop,
    'monitor': Monitor,
    'printer': Printer,
    'key': Key,
    'lock': Lock,
    'map-pinned': MapPinned,
    'backpack': Backpack,
    'luggage': Luggage,
    'ticket': Ticket,
}